python edit_dist_align.py --input  CCNG_CKEY.txt --output CCNG_CKEY.align 
python edit_dist_align.py --input  CCNG_CKIM.txt --output CCNG_CKIM.align 
python edit_dist_align.py --input  CCNG_DKIM.txt --output CCNG_DKIM.align 
python edit_dist_align.py --input  CCNG_EKIM.txt --output CCNG_EKIM.align 
python edit_dist_align.py --input  CCNG_GKES.txt --output CCNG_GKES.align 
python edit_dist_align.py --input  CCNG_GKIM.txt --output CCNG_GKIM.align 
python edit_dist_align.py --input  CCNG_HDSK.txt --output CCNG_HDSK.align 
python edit_dist_align.py --input  CCNG_HKES.txt --output CCNG_HKES.align 
python edit_dist_align.py --input  CCNG_IKES.txt --output CCNG_IKES.align 
python edit_dist_align.py --input  CCNG_JKES.txt --output CCNG_JKES.align 
python edit_dist_align.py --input  CCNG_JKIM.txt --output CCNG_JKIM.align 
python edit_dist_align.py --input  CCNG_KKEY.txt --output CCNG_KKEY.align 
python edit_dist_align.py --input  CCNG_KKIM.txt --output CCNG_KKIM.align 
python edit_dist_align.py --input  CCNG_NKES.txt --output CCNG_NKES.align 
python edit_dist_align.py --input  CCNG_SCYD.txt --output CCNG_SCYD.align 
python edit_dist_align.py --input  CCNG_YKEY.txt --output CCNG_YKEY.align 
python edit_dist_align.py --input  CCNG_YKIM.txt --output CCNG_YKIM.align 
python edit_dist_align.py --input  CCNG_YSEO.txt --output CCNG_YSEO.align 
python edit_dist_align.py --input  CCNG_YSNG.txt --output CCNG_YSNG.align 
python edit_dist_align.py --input  CCNG_ZKES.txt --output CCNG_ZKES.align 
python edit_dist_align.py --input  CCNG_ZSUN.txt --output CCNG_ZSUN.align 
python edit_dist_align.py --input  CKEY_CKIM.txt --output CKEY_CKIM.align 
python edit_dist_align.py --input  CKEY_DKIM.txt --output CKEY_DKIM.align 
python edit_dist_align.py --input  CKEY_EKIM.txt --output CKEY_EKIM.align 
python edit_dist_align.py --input  CKEY_GKES.txt --output CKEY_GKES.align 
python edit_dist_align.py --input  CKEY_GKIM.txt --output CKEY_GKIM.align 
python edit_dist_align.py --input  CKEY_HDSK.txt --output CKEY_HDSK.align 
python edit_dist_align.py --input  CKEY_HKES.txt --output CKEY_HKES.align 
python edit_dist_align.py --input  CKEY_IKES.txt --output CKEY_IKES.align 
python edit_dist_align.py --input  CKEY_JKES.txt --output CKEY_JKES.align 
python edit_dist_align.py --input  CKEY_JKIM.txt --output CKEY_JKIM.align 
python edit_dist_align.py --input  CKEY_KKEY.txt --output CKEY_KKEY.align 
python edit_dist_align.py --input  CKEY_KKIM.txt --output CKEY_KKIM.align 
python edit_dist_align.py --input  CKEY_NKES.txt --output CKEY_NKES.align 
python edit_dist_align.py --input  CKEY_SCYD.txt --output CKEY_SCYD.align 
python edit_dist_align.py --input  CKEY_YKEY.txt --output CKEY_YKEY.align 
python edit_dist_align.py --input  CKEY_YKIM.txt --output CKEY_YKIM.align 
python edit_dist_align.py --input  CKEY_YSEO.txt --output CKEY_YSEO.align 
python edit_dist_align.py --input  CKEY_YSNG.txt --output CKEY_YSNG.align 
python edit_dist_align.py --input  CKEY_ZKES.txt --output CKEY_ZKES.align 
python edit_dist_align.py --input  CKEY_ZSUN.txt --output CKEY_ZSUN.align 
python edit_dist_align.py --input  CKIM_DKIM.txt --output CKIM_DKIM.align 
python edit_dist_align.py --input  CKIM_EKIM.txt --output CKIM_EKIM.align 
python edit_dist_align.py --input  CKIM_GKES.txt --output CKIM_GKES.align 
python edit_dist_align.py --input  CKIM_GKIM.txt --output CKIM_GKIM.align 
python edit_dist_align.py --input  CKIM_HDSK.txt --output CKIM_HDSK.align 
python edit_dist_align.py --input  CKIM_HKES.txt --output CKIM_HKES.align 
python edit_dist_align.py --input  CKIM_IKES.txt --output CKIM_IKES.align 
python edit_dist_align.py --input  CKIM_JKES.txt --output CKIM_JKES.align 
python edit_dist_align.py --input  CKIM_JKIM.txt --output CKIM_JKIM.align 
python edit_dist_align.py --input  CKIM_KKEY.txt --output CKIM_KKEY.align 
python edit_dist_align.py --input  CKIM_KKIM.txt --output CKIM_KKIM.align 
python edit_dist_align.py --input  CKIM_NKES.txt --output CKIM_NKES.align 
python edit_dist_align.py --input  CKIM_SCYD.txt --output CKIM_SCYD.align 
python edit_dist_align.py --input  CKIM_YKEY.txt --output CKIM_YKEY.align 
python edit_dist_align.py --input  CKIM_YKIM.txt --output CKIM_YKIM.align 
python edit_dist_align.py --input  CKIM_YSEO.txt --output CKIM_YSEO.align 
python edit_dist_align.py --input  CKIM_YSNG.txt --output CKIM_YSNG.align 
python edit_dist_align.py --input  CKIM_ZKES.txt --output CKIM_ZKES.align 
python edit_dist_align.py --input  CKIM_ZSUN.txt --output CKIM_ZSUN.align 
python edit_dist_align.py --input  DKIM_EKIM.txt --output DKIM_EKIM.align 
python edit_dist_align.py --input  DKIM_GKES.txt --output DKIM_GKES.align 
python edit_dist_align.py --input  DKIM_GKIM.txt --output DKIM_GKIM.align 
python edit_dist_align.py --input  DKIM_HDSK.txt --output DKIM_HDSK.align 
python edit_dist_align.py --input  DKIM_HKES.txt --output DKIM_HKES.align 
python edit_dist_align.py --input  DKIM_IKES.txt --output DKIM_IKES.align 
python edit_dist_align.py --input  DKIM_JKES.txt --output DKIM_JKES.align 
python edit_dist_align.py --input  DKIM_JKIM.txt --output DKIM_JKIM.align 
python edit_dist_align.py --input  DKIM_KKEY.txt --output DKIM_KKEY.align 
python edit_dist_align.py --input  DKIM_KKIM.txt --output DKIM_KKIM.align 
python edit_dist_align.py --input  DKIM_NKES.txt --output DKIM_NKES.align 
python edit_dist_align.py --input  DKIM_SCYD.txt --output DKIM_SCYD.align 
python edit_dist_align.py --input  DKIM_YKEY.txt --output DKIM_YKEY.align 
python edit_dist_align.py --input  DKIM_YKIM.txt --output DKIM_YKIM.align 
python edit_dist_align.py --input  DKIM_YSEO.txt --output DKIM_YSEO.align 
python edit_dist_align.py --input  DKIM_YSNG.txt --output DKIM_YSNG.align 
python edit_dist_align.py --input  DKIM_ZKES.txt --output DKIM_ZKES.align 
python edit_dist_align.py --input  DKIM_ZSUN.txt --output DKIM_ZSUN.align 
python edit_dist_align.py --input  EKIM_GKES.txt --output EKIM_GKES.align 
python edit_dist_align.py --input  EKIM_GKIM.txt --output EKIM_GKIM.align 
python edit_dist_align.py --input  EKIM_HDSK.txt --output EKIM_HDSK.align 
python edit_dist_align.py --input  EKIM_HKES.txt --output EKIM_HKES.align 
python edit_dist_align.py --input  EKIM_IKES.txt --output EKIM_IKES.align 
python edit_dist_align.py --input  EKIM_JKES.txt --output EKIM_JKES.align 
python edit_dist_align.py --input  EKIM_JKIM.txt --output EKIM_JKIM.align 
python edit_dist_align.py --input  EKIM_KKEY.txt --output EKIM_KKEY.align 
python edit_dist_align.py --input  EKIM_KKIM.txt --output EKIM_KKIM.align 
python edit_dist_align.py --input  EKIM_NKES.txt --output EKIM_NKES.align 
python edit_dist_align.py --input  EKIM_SCYD.txt --output EKIM_SCYD.align 
python edit_dist_align.py --input  EKIM_YKEY.txt --output EKIM_YKEY.align 
python edit_dist_align.py --input  EKIM_YKIM.txt --output EKIM_YKIM.align 
python edit_dist_align.py --input  EKIM_YSEO.txt --output EKIM_YSEO.align 
python edit_dist_align.py --input  EKIM_YSNG.txt --output EKIM_YSNG.align 
python edit_dist_align.py --input  EKIM_ZKES.txt --output EKIM_ZKES.align 
python edit_dist_align.py --input  EKIM_ZSUN.txt --output EKIM_ZSUN.align 
python edit_dist_align.py --input  GKES_GKIM.txt --output GKES_GKIM.align 
python edit_dist_align.py --input  GKES_HDSK.txt --output GKES_HDSK.align 
python edit_dist_align.py --input  GKES_HKES.txt --output GKES_HKES.align 
python edit_dist_align.py --input  GKES_IKES.txt --output GKES_IKES.align 
python edit_dist_align.py --input  GKES_JKES.txt --output GKES_JKES.align 
python edit_dist_align.py --input  GKES_JKIM.txt --output GKES_JKIM.align 
python edit_dist_align.py --input  GKES_KKEY.txt --output GKES_KKEY.align 
python edit_dist_align.py --input  GKES_KKIM.txt --output GKES_KKIM.align 
python edit_dist_align.py --input  GKES_NKES.txt --output GKES_NKES.align 
python edit_dist_align.py --input  GKES_SCYD.txt --output GKES_SCYD.align 
python edit_dist_align.py --input  GKES_YKEY.txt --output GKES_YKEY.align 
python edit_dist_align.py --input  GKES_YKIM.txt --output GKES_YKIM.align 
python edit_dist_align.py --input  GKES_YSEO.txt --output GKES_YSEO.align 
python edit_dist_align.py --input  GKES_YSNG.txt --output GKES_YSNG.align 
python edit_dist_align.py --input  GKES_ZKES.txt --output GKES_ZKES.align 
python edit_dist_align.py --input  GKES_ZSUN.txt --output GKES_ZSUN.align 
python edit_dist_align.py --input  GKIM_HDSK.txt --output GKIM_HDSK.align 
python edit_dist_align.py --input  GKIM_HKES.txt --output GKIM_HKES.align 
python edit_dist_align.py --input  GKIM_IKES.txt --output GKIM_IKES.align 
python edit_dist_align.py --input  GKIM_JKES.txt --output GKIM_JKES.align 
python edit_dist_align.py --input  GKIM_JKIM.txt --output GKIM_JKIM.align 
python edit_dist_align.py --input  GKIM_KKEY.txt --output GKIM_KKEY.align 
python edit_dist_align.py --input  GKIM_KKIM.txt --output GKIM_KKIM.align 
python edit_dist_align.py --input  GKIM_NKES.txt --output GKIM_NKES.align 
python edit_dist_align.py --input  GKIM_SCYD.txt --output GKIM_SCYD.align 
python edit_dist_align.py --input  GKIM_YKEY.txt --output GKIM_YKEY.align 
python edit_dist_align.py --input  GKIM_YKIM.txt --output GKIM_YKIM.align 
python edit_dist_align.py --input  GKIM_YSEO.txt --output GKIM_YSEO.align 
python edit_dist_align.py --input  GKIM_YSNG.txt --output GKIM_YSNG.align 
python edit_dist_align.py --input  GKIM_ZKES.txt --output GKIM_ZKES.align 
python edit_dist_align.py --input  GKIM_ZSUN.txt --output GKIM_ZSUN.align 
python edit_dist_align.py --input  HDSK_HKES.txt --output HDSK_HKES.align 
python edit_dist_align.py --input  HDSK_IKES.txt --output HDSK_IKES.align 
python edit_dist_align.py --input  HDSK_JKES.txt --output HDSK_JKES.align 
python edit_dist_align.py --input  HDSK_JKIM.txt --output HDSK_JKIM.align 
python edit_dist_align.py --input  HDSK_KKEY.txt --output HDSK_KKEY.align 
python edit_dist_align.py --input  HDSK_KKIM.txt --output HDSK_KKIM.align 
python edit_dist_align.py --input  HDSK_NKES.txt --output HDSK_NKES.align 
python edit_dist_align.py --input  HDSK_SCYD.txt --output HDSK_SCYD.align 
python edit_dist_align.py --input  HDSK_YKEY.txt --output HDSK_YKEY.align 
python edit_dist_align.py --input  HDSK_YKIM.txt --output HDSK_YKIM.align 
python edit_dist_align.py --input  HDSK_YSEO.txt --output HDSK_YSEO.align 
python edit_dist_align.py --input  HDSK_YSNG.txt --output HDSK_YSNG.align 
python edit_dist_align.py --input  HDSK_ZKES.txt --output HDSK_ZKES.align 
python edit_dist_align.py --input  HDSK_ZSUN.txt --output HDSK_ZSUN.align 
python edit_dist_align.py --input  HKES_IKES.txt --output HKES_IKES.align 
python edit_dist_align.py --input  HKES_JKES.txt --output HKES_JKES.align 
python edit_dist_align.py --input  HKES_JKIM.txt --output HKES_JKIM.align 
python edit_dist_align.py --input  HKES_KKEY.txt --output HKES_KKEY.align 
python edit_dist_align.py --input  HKES_KKIM.txt --output HKES_KKIM.align 
python edit_dist_align.py --input  HKES_NKES.txt --output HKES_NKES.align 
python edit_dist_align.py --input  HKES_SCYD.txt --output HKES_SCYD.align 
python edit_dist_align.py --input  HKES_YKEY.txt --output HKES_YKEY.align 
python edit_dist_align.py --input  HKES_YKIM.txt --output HKES_YKIM.align 
python edit_dist_align.py --input  HKES_YSEO.txt --output HKES_YSEO.align 
python edit_dist_align.py --input  HKES_YSNG.txt --output HKES_YSNG.align 
python edit_dist_align.py --input  HKES_ZKES.txt --output HKES_ZKES.align 
python edit_dist_align.py --input  HKES_ZSUN.txt --output HKES_ZSUN.align 
python edit_dist_align.py --input  IKES_JKES.txt --output IKES_JKES.align 
python edit_dist_align.py --input  IKES_JKIM.txt --output IKES_JKIM.align 
python edit_dist_align.py --input  IKES_KKEY.txt --output IKES_KKEY.align 
python edit_dist_align.py --input  IKES_KKIM.txt --output IKES_KKIM.align 
python edit_dist_align.py --input  IKES_NKES.txt --output IKES_NKES.align 
python edit_dist_align.py --input  IKES_SCYD.txt --output IKES_SCYD.align 
python edit_dist_align.py --input  IKES_YKEY.txt --output IKES_YKEY.align 
python edit_dist_align.py --input  IKES_YKIM.txt --output IKES_YKIM.align 
python edit_dist_align.py --input  IKES_YSEO.txt --output IKES_YSEO.align 
python edit_dist_align.py --input  IKES_YSNG.txt --output IKES_YSNG.align 
python edit_dist_align.py --input  IKES_ZKES.txt --output IKES_ZKES.align 
python edit_dist_align.py --input  IKES_ZSUN.txt --output IKES_ZSUN.align 
python edit_dist_align.py --input  JKES_JKIM.txt --output JKES_JKIM.align 
python edit_dist_align.py --input  JKES_KKEY.txt --output JKES_KKEY.align 
python edit_dist_align.py --input  JKES_KKIM.txt --output JKES_KKIM.align 
python edit_dist_align.py --input  JKES_NKES.txt --output JKES_NKES.align 
python edit_dist_align.py --input  JKES_SCYD.txt --output JKES_SCYD.align 
python edit_dist_align.py --input  JKES_YKEY.txt --output JKES_YKEY.align 
python edit_dist_align.py --input  JKES_YKIM.txt --output JKES_YKIM.align 
python edit_dist_align.py --input  JKES_YSEO.txt --output JKES_YSEO.align 
python edit_dist_align.py --input  JKES_YSNG.txt --output JKES_YSNG.align 
python edit_dist_align.py --input  JKES_ZKES.txt --output JKES_ZKES.align 
python edit_dist_align.py --input  JKES_ZSUN.txt --output JKES_ZSUN.align 
python edit_dist_align.py --input  JKIM_KKEY.txt --output JKIM_KKEY.align 
python edit_dist_align.py --input  JKIM_KKIM.txt --output JKIM_KKIM.align 
python edit_dist_align.py --input  JKIM_NKES.txt --output JKIM_NKES.align 
python edit_dist_align.py --input  JKIM_SCYD.txt --output JKIM_SCYD.align 
python edit_dist_align.py --input  JKIM_YKEY.txt --output JKIM_YKEY.align 
python edit_dist_align.py --input  JKIM_YKIM.txt --output JKIM_YKIM.align 
python edit_dist_align.py --input  JKIM_YSEO.txt --output JKIM_YSEO.align 
python edit_dist_align.py --input  JKIM_YSNG.txt --output JKIM_YSNG.align 
python edit_dist_align.py --input  JKIM_ZKES.txt --output JKIM_ZKES.align 
python edit_dist_align.py --input  JKIM_ZSUN.txt --output JKIM_ZSUN.align 
python edit_dist_align.py --input  KKEY_KKIM.txt --output KKEY_KKIM.align 
python edit_dist_align.py --input  KKEY_NKES.txt --output KKEY_NKES.align 
python edit_dist_align.py --input  KKEY_SCYD.txt --output KKEY_SCYD.align 
python edit_dist_align.py --input  KKEY_YKEY.txt --output KKEY_YKEY.align 
python edit_dist_align.py --input  KKEY_YKIM.txt --output KKEY_YKIM.align 
python edit_dist_align.py --input  KKEY_YSEO.txt --output KKEY_YSEO.align 
python edit_dist_align.py --input  KKEY_YSNG.txt --output KKEY_YSNG.align 
python edit_dist_align.py --input  KKEY_ZKES.txt --output KKEY_ZKES.align 
python edit_dist_align.py --input  KKIM_NKES.txt --output KKIM_NKES.align 
python edit_dist_align.py --input  KKIM_SCYD.txt --output KKIM_SCYD.align 
python edit_dist_align.py --input  KKIM_YKEY.txt --output KKIM_YKEY.align 
python edit_dist_align.py --input  KKIM_YKIM.txt --output KKIM_YKIM.align 
python edit_dist_align.py --input  KKIM_YSEO.txt --output KKIM_YSEO.align 
python edit_dist_align.py --input  KKIM_YSNG.txt --output KKIM_YSNG.align 
python edit_dist_align.py --input  KKIM_ZKES.txt --output KKIM_ZKES.align 
python edit_dist_align.py --input  NKES_SCYD.txt --output NKES_SCYD.align 
python edit_dist_align.py --input  NKES_YKEY.txt --output NKES_YKEY.align 
python edit_dist_align.py --input  NKES_YKIM.txt --output NKES_YKIM.align 
python edit_dist_align.py --input  NKES_YSEO.txt --output NKES_YSEO.align 
python edit_dist_align.py --input  NKES_YSNG.txt --output NKES_YSNG.align 
python edit_dist_align.py --input  NKES_ZKES.txt --output NKES_ZKES.align 
python edit_dist_align.py --input  SCYD_YKEY.txt --output SCYD_YKEY.align 
python edit_dist_align.py --input  SCYD_YKIM.txt --output SCYD_YKIM.align 
python edit_dist_align.py --input  SCYD_YSEO.txt --output SCYD_YSEO.align 
python edit_dist_align.py --input  SCYD_YSNG.txt --output SCYD_YSNG.align 
python edit_dist_align.py --input  SCYD_ZKES.txt --output SCYD_ZKES.align 
python edit_dist_align.py --input  YKEY_YKIM.txt --output YKEY_YKIM.align 
python edit_dist_align.py --input  YKEY_YSEO.txt --output YKEY_YSEO.align 
python edit_dist_align.py --input  YKEY_YSNG.txt --output YKEY_YSNG.align 
python edit_dist_align.py --input  YKEY_ZKES.txt --output YKEY_ZKES.align 
python edit_dist_align.py --input  YKIM_YSEO.txt --output YKIM_YSEO.align 
python edit_dist_align.py --input  YKIM_YSNG.txt --output YKIM_YSNG.align 
python edit_dist_align.py --input  YKIM_ZKES.txt --output YKIM_ZKES.align 
python edit_dist_align.py --input  YSEO_YSNG.txt --output YSEO_YSNG.align 
python edit_dist_align.py --input  YSEO_ZKES.txt --output YSEO_ZKES.align 
python edit_dist_align.py --input  YSNG_ZKES.txt --output YSNG_ZKES.align 
python edit_dist_align.py --input  ZSUN_KKEY.txt --output ZSUN_KKEY.align 
python edit_dist_align.py --input  ZSUN_KKIM.txt --output ZSUN_KKIM.align 
python edit_dist_align.py --input  ZSUN_NKES.txt --output ZSUN_NKES.align 
python edit_dist_align.py --input  ZSUN_SCYD.txt --output ZSUN_SCYD.align 
python edit_dist_align.py --input  ZSUN_YKEY.txt --output ZSUN_YKEY.align 
python edit_dist_align.py --input  ZSUN_YKIM.txt --output ZSUN_YKIM.align 
python edit_dist_align.py --input  ZSUN_YSEO.txt --output ZSUN_YSEO.align 
python edit_dist_align.py --input  ZSUN_YSNG.txt --output ZSUN_YSNG.align 
python edit_dist_align.py --input  ZSUN_ZKES.txt --output ZSUN_ZKES.align 
