gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_CKEY.align > CCNG_CKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_CKIM.align > CCNG_CKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_DKIM.align > CCNG_DKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_EKIM.align > CCNG_EKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_GKES.align > CCNG_GKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_GKIM.align > CCNG_GKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_HDSK.align > CCNG_HDSK.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_HKES.align > CCNG_HKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_IKES.align > CCNG_IKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_JKES.align > CCNG_JKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_JKIM.align > CCNG_JKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_KKEY.align > CCNG_KKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_KKIM.align > CCNG_KKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_NKES.align > CCNG_NKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_SCYD.align > CCNG_SCYD.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_YKEY.align > CCNG_YKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_YKIM.align > CCNG_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_YSEO.align > CCNG_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_YSNG.align > CCNG_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_ZKES.align > CCNG_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CCNG_ZSUN.align > CCNG_ZSUN.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_CKIM.align > CKEY_CKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_DKIM.align > CKEY_DKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_EKIM.align > CKEY_EKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_GKES.align > CKEY_GKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_GKIM.align > CKEY_GKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_HDSK.align > CKEY_HDSK.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_HKES.align > CKEY_HKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_IKES.align > CKEY_IKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_JKES.align > CKEY_JKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_JKIM.align > CKEY_JKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_KKEY.align > CKEY_KKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_KKIM.align > CKEY_KKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_NKES.align > CKEY_NKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_SCYD.align > CKEY_SCYD.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_YKEY.align > CKEY_YKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_YKIM.align > CKEY_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_YSEO.align > CKEY_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_YSNG.align > CKEY_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_ZKES.align > CKEY_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKEY_ZSUN.align > CKEY_ZSUN.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_DKIM.align > CKIM_DKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_EKIM.align > CKIM_EKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_GKES.align > CKIM_GKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_GKIM.align > CKIM_GKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_HDSK.align > CKIM_HDSK.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_HKES.align > CKIM_HKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_IKES.align > CKIM_IKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_JKES.align > CKIM_JKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_JKIM.align > CKIM_JKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_KKEY.align > CKIM_KKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_KKIM.align > CKIM_KKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_NKES.align > CKIM_NKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_SCYD.align > CKIM_SCYD.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_YKEY.align > CKIM_YKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_YKIM.align > CKIM_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_YSEO.align > CKIM_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_YSNG.align > CKIM_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_ZKES.align > CKIM_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\CKIM_ZSUN.align > CKIM_ZSUN.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_EKIM.align > DKIM_EKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_GKES.align > DKIM_GKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_GKIM.align > DKIM_GKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_HDSK.align > DKIM_HDSK.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_HKES.align > DKIM_HKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_IKES.align > DKIM_IKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_JKES.align > DKIM_JKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_JKIM.align > DKIM_JKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_KKEY.align > DKIM_KKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_KKIM.align > DKIM_KKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_NKES.align > DKIM_NKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_SCYD.align > DKIM_SCYD.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_YKEY.align > DKIM_YKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_YKIM.align > DKIM_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_YSEO.align > DKIM_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_YSNG.align > DKIM_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_ZKES.align > DKIM_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\DKIM_ZSUN.align > DKIM_ZSUN.html 
gawk -f seq_align_to_html.awk ..\pairs_01\EKIM_GKES.align > EKIM_GKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\EKIM_GKIM.align > EKIM_GKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\EKIM_HDSK.align > EKIM_HDSK.html 
gawk -f seq_align_to_html.awk ..\pairs_01\EKIM_HKES.align > EKIM_HKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\EKIM_IKES.align > EKIM_IKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\EKIM_JKES.align > EKIM_JKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\EKIM_JKIM.align > EKIM_JKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\EKIM_KKEY.align > EKIM_KKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\EKIM_KKIM.align > EKIM_KKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\EKIM_NKES.align > EKIM_NKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\EKIM_SCYD.align > EKIM_SCYD.html 
gawk -f seq_align_to_html.awk ..\pairs_01\EKIM_YKEY.align > EKIM_YKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\EKIM_YKIM.align > EKIM_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\EKIM_YSEO.align > EKIM_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\EKIM_YSNG.align > EKIM_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\EKIM_ZKES.align > EKIM_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\EKIM_ZSUN.align > EKIM_ZSUN.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKES_GKIM.align > GKES_GKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKES_HDSK.align > GKES_HDSK.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKES_HKES.align > GKES_HKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKES_IKES.align > GKES_IKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKES_JKES.align > GKES_JKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKES_JKIM.align > GKES_JKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKES_KKEY.align > GKES_KKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKES_KKIM.align > GKES_KKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKES_NKES.align > GKES_NKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKES_SCYD.align > GKES_SCYD.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKES_YKEY.align > GKES_YKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKES_YKIM.align > GKES_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKES_YSEO.align > GKES_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKES_YSNG.align > GKES_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKES_ZKES.align > GKES_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKES_ZSUN.align > GKES_ZSUN.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKIM_HDSK.align > GKIM_HDSK.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKIM_HKES.align > GKIM_HKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKIM_IKES.align > GKIM_IKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKIM_JKES.align > GKIM_JKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKIM_JKIM.align > GKIM_JKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKIM_KKEY.align > GKIM_KKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKIM_KKIM.align > GKIM_KKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKIM_NKES.align > GKIM_NKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKIM_SCYD.align > GKIM_SCYD.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKIM_YKEY.align > GKIM_YKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKIM_YKIM.align > GKIM_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKIM_YSEO.align > GKIM_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKIM_YSNG.align > GKIM_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKIM_ZKES.align > GKIM_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\GKIM_ZSUN.align > GKIM_ZSUN.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HDSK_HKES.align > HDSK_HKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HDSK_IKES.align > HDSK_IKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HDSK_JKES.align > HDSK_JKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HDSK_JKIM.align > HDSK_JKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HDSK_KKEY.align > HDSK_KKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HDSK_KKIM.align > HDSK_KKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HDSK_NKES.align > HDSK_NKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HDSK_SCYD.align > HDSK_SCYD.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HDSK_YKEY.align > HDSK_YKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HDSK_YKIM.align > HDSK_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HDSK_YSEO.align > HDSK_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HDSK_YSNG.align > HDSK_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HDSK_ZKES.align > HDSK_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HDSK_ZSUN.align > HDSK_ZSUN.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HKES_IKES.align > HKES_IKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HKES_JKES.align > HKES_JKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HKES_JKIM.align > HKES_JKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HKES_KKEY.align > HKES_KKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HKES_KKIM.align > HKES_KKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HKES_NKES.align > HKES_NKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HKES_SCYD.align > HKES_SCYD.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HKES_YKEY.align > HKES_YKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HKES_YKIM.align > HKES_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HKES_YSEO.align > HKES_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HKES_YSNG.align > HKES_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HKES_ZKES.align > HKES_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\HKES_ZSUN.align > HKES_ZSUN.html 
gawk -f seq_align_to_html.awk ..\pairs_01\IKES_JKES.align > IKES_JKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\IKES_JKIM.align > IKES_JKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\IKES_KKEY.align > IKES_KKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\IKES_KKIM.align > IKES_KKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\IKES_NKES.align > IKES_NKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\IKES_SCYD.align > IKES_SCYD.html 
gawk -f seq_align_to_html.awk ..\pairs_01\IKES_YKEY.align > IKES_YKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\IKES_YKIM.align > IKES_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\IKES_YSEO.align > IKES_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\IKES_YSNG.align > IKES_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\IKES_ZKES.align > IKES_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\IKES_ZSUN.align > IKES_ZSUN.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKES_JKIM.align > JKES_JKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKES_KKEY.align > JKES_KKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKES_KKIM.align > JKES_KKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKES_NKES.align > JKES_NKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKES_SCYD.align > JKES_SCYD.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKES_YKEY.align > JKES_YKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKES_YKIM.align > JKES_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKES_YSEO.align > JKES_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKES_YSNG.align > JKES_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKES_ZKES.align > JKES_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKES_ZSUN.align > JKES_ZSUN.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKIM_KKEY.align > JKIM_KKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKIM_KKIM.align > JKIM_KKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKIM_NKES.align > JKIM_NKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKIM_SCYD.align > JKIM_SCYD.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKIM_YKEY.align > JKIM_YKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKIM_YKIM.align > JKIM_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKIM_YSEO.align > JKIM_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKIM_YSNG.align > JKIM_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKIM_ZKES.align > JKIM_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\JKIM_ZSUN.align > JKIM_ZSUN.html 
gawk -f seq_align_to_html.awk ..\pairs_01\KKEY_KKIM.align > KKEY_KKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\KKEY_NKES.align > KKEY_NKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\KKEY_SCYD.align > KKEY_SCYD.html 
gawk -f seq_align_to_html.awk ..\pairs_01\KKEY_YKEY.align > KKEY_YKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\KKEY_YKIM.align > KKEY_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\KKEY_YSEO.align > KKEY_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\KKEY_YSNG.align > KKEY_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\KKEY_ZKES.align > KKEY_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\KKIM_NKES.align > KKIM_NKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\KKIM_SCYD.align > KKIM_SCYD.html 
gawk -f seq_align_to_html.awk ..\pairs_01\KKIM_YKEY.align > KKIM_YKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\KKIM_YKIM.align > KKIM_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\KKIM_YSEO.align > KKIM_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\KKIM_YSNG.align > KKIM_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\KKIM_ZKES.align > KKIM_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\NKES_SCYD.align > NKES_SCYD.html 
gawk -f seq_align_to_html.awk ..\pairs_01\NKES_YKEY.align > NKES_YKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\NKES_YKIM.align > NKES_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\NKES_YSEO.align > NKES_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\NKES_YSNG.align > NKES_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\NKES_ZKES.align > NKES_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\SCYD_YKEY.align > SCYD_YKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\SCYD_YKIM.align > SCYD_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\SCYD_YSEO.align > SCYD_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\SCYD_YSNG.align > SCYD_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\SCYD_ZKES.align > SCYD_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\YKEY_YKIM.align > YKEY_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\YKEY_YSEO.align > YKEY_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\YKEY_YSNG.align > YKEY_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\YKEY_ZKES.align > YKEY_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\YKIM_YSEO.align > YKIM_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\YKIM_YSNG.align > YKIM_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\YKIM_ZKES.align > YKIM_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\YSEO_YSNG.align > YSEO_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\YSEO_ZKES.align > YSEO_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\YSNG_ZKES.align > YSNG_ZKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\ZSUN_KKEY.align > ZSUN_KKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\ZSUN_KKIM.align > ZSUN_KKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\ZSUN_NKES.align > ZSUN_NKES.html 
gawk -f seq_align_to_html.awk ..\pairs_01\ZSUN_SCYD.align > ZSUN_SCYD.html 
gawk -f seq_align_to_html.awk ..\pairs_01\ZSUN_YKEY.align > ZSUN_YKEY.html 
gawk -f seq_align_to_html.awk ..\pairs_01\ZSUN_YKIM.align > ZSUN_YKIM.html 
gawk -f seq_align_to_html.awk ..\pairs_01\ZSUN_YSEO.align > ZSUN_YSEO.html 
gawk -f seq_align_to_html.awk ..\pairs_01\ZSUN_YSNG.align > ZSUN_YSNG.html 
gawk -f seq_align_to_html.awk ..\pairs_01\ZSUN_ZKES.align > ZSUN_ZKES.html 
